{% set name = "pcntoolkit" %}
{% set version = "0.30.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pcntoolkit-{{ version }}.tar.gz
  sha256: 7452ebc3669a11638bc705d9ea8eabf28dee933da58e1d02279626598feb9245

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pymc
    - pytorch
    - cpuonly
    - scikit-learn
    - matplotlib-base
    - six
    - sphinx-tabs
    - nibabel
  pip:
    - bspline

test:
  imports:
    - pcntoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/amarquand/PCNtoolkit
  summary: Predictive Clinical Neuroscience toolkit
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AuguB
