{% set name = "pcntoolkit" %}
{% set version = "0.30.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AuguB/PCNtoolkit/archive/refs/tags/conda.tar.gz
  sha256: 795574f97a7bbf2c57b2f9ed2415201d52e5e2f3646ed8719439796b1bc5b4e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps

requirements:
  host:
    - python >=3.10,<3.13
    - pip
    - poetry
    - setuptools
  run:
    - python >=3.10,<3.13
    - nibabel >=5.3.1
    - pymc >=5.17.0
    - scikit-learn >=1.5.2
    - seaborn >=0.13.2
    - six >=1.16.0

about:
  home: http://github.com/amarquand/PCNtoolkit
  summary: Predictive Clinical Neuroscience toolkit
  license: GPL-3.0-only
  license_file: https://www.gnu.org/licenses/gpl-3.0.txt

extra:
  recipe-maintainers:
    - amarquand
    - AuguB

test:
  imports:
    - package_name
